// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HealthLiveHealthGetApiV1HealthLiveResponse, HealthReadyHealthGetApiV1HealthReadyResponse, HealthDependenciesHealthGetApiV1HealthDependenciesResponse, LoginLoginAccessTokenPostApiV1LoginAccessTokenData, LoginLoginAccessTokenPostApiV1LoginAccessTokenResponse, LoginTestTokenPostApiV1LoginTestTokenResponse, LoginRecoverPasswordPostApiV1PasswordRecoveryEmailData, LoginRecoverPasswordPostApiV1PasswordRecoveryEmailResponse, LoginResetPasswordPostApiV1ResetPasswordData, LoginResetPasswordPostApiV1ResetPasswordResponse, LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailData, LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailResponse, PrivateCreateUserPostApiV1PrivateUsersData, PrivateCreateUserPostApiV1PrivateUsersResponse, UsersReadUsersGetApiV1UsersData, UsersReadUsersGetApiV1UsersResponse, UsersCreateUserPostApiV1UsersData, UsersCreateUserPostApiV1UsersResponse, UsersReadUserMeGetApiV1UsersMeResponse, UsersDeleteUserMeDeleteApiV1UsersMeResponse, UsersUpdateUserMePatchApiV1UsersMeData, UsersUpdateUserMePatchApiV1UsersMeResponse, UsersUpdatePasswordMePatchApiV1UsersMePasswordData, UsersUpdatePasswordMePatchApiV1UsersMePasswordResponse, UsersRegisterUserPostApiV1UsersSignupData, UsersRegisterUserPostApiV1UsersSignupResponse, UsersReadUserByIdGetApiV1UsersUserIdData, UsersReadUserByIdGetApiV1UsersUserIdResponse, UsersUpdateUserPatchApiV1UsersUserIdData, UsersUpdateUserPatchApiV1UsersUserIdResponse, UsersDeleteUserDeleteApiV1UsersUserIdData, UsersDeleteUserDeleteApiV1UsersUserIdResponse, UtilsTestEmailPostApiV1UtilsTestEmailData, UtilsTestEmailPostApiV1UtilsTestEmailResponse } from './types.gen';

export class HealthService {
    /**
     * Live Health
     * Process-only liveness endpoint; intentionally performs no dependency probe.
     * @returns LiveHealthResponse Successful Response
     * @throws ApiError
     */
    public static liveHealthGetApiV1HealthLive(): CancelablePromise<HealthLiveHealthGetApiV1HealthLiveResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/health/live',
            errors: {
                500: 'Internal Server Error'
            }
        });
    }

    /**
     * Ready Health
     * @returns ReadyHealthResponse Successful Response
     * @throws ApiError
     */
    public static readyHealthGetApiV1HealthReady(): CancelablePromise<HealthReadyHealthGetApiV1HealthReadyResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/health/ready',
            errors: {
                500: 'Internal Server Error',
                503: 'Service Unavailable'
            }
        });
    }

    /**
     * Dependencies Health
     * @returns DependenciesHealthResponse Successful Response
     * @throws ApiError
     */
    public static dependenciesHealthGetApiV1HealthDependencies(): CancelablePromise<HealthDependenciesHealthGetApiV1HealthDependenciesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/health/dependencies',
            errors: {
                500: 'Internal Server Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessTokenPostApiV1LoginAccessToken(data: LoginLoginAccessTokenPostApiV1LoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenPostApiV1LoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testTokenPostApiV1LoginTestToken(): CancelablePromise<LoginTestTokenPostApiV1LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }

    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPasswordPostApiV1PasswordRecoveryEmail(data: LoginRecoverPasswordPostApiV1PasswordRecoveryEmailData): CancelablePromise<LoginRecoverPasswordPostApiV1PasswordRecoveryEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPasswordPostApiV1ResetPassword(data: LoginResetPasswordPostApiV1ResetPasswordData): CancelablePromise<LoginResetPasswordPostApiV1ResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmail(data: LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailData): CancelablePromise<LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUserPostApiV1PrivateUsers(data: PrivateCreateUserPostApiV1PrivateUsersData): CancelablePromise<PrivateCreateUserPostApiV1PrivateUsersResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsersGetApiV1Users(data: UsersReadUsersGetApiV1UsersData = {}): CancelablePromise<UsersReadUsersGetApiV1UsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUserPostApiV1Users(data: UsersCreateUserPostApiV1UsersData): CancelablePromise<UsersCreateUserPostApiV1UsersResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMeGetApiV1UsersMe(): CancelablePromise<UsersReadUserMeGetApiV1UsersMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }

    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMeDeleteApiV1UsersMe(): CancelablePromise<UsersDeleteUserMeDeleteApiV1UsersMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }

    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMePatchApiV1UsersMe(data: UsersUpdateUserMePatchApiV1UsersMeData): CancelablePromise<UsersUpdateUserMePatchApiV1UsersMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMePatchApiV1UsersMePassword(data: UsersUpdatePasswordMePatchApiV1UsersMePasswordData): CancelablePromise<UsersUpdatePasswordMePatchApiV1UsersMePasswordResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUserPostApiV1UsersSignup(data: UsersRegisterUserPostApiV1UsersSignupData): CancelablePromise<UsersRegisterUserPostApiV1UsersSignupResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserByIdGetApiV1UsersUserId(data: UsersReadUserByIdGetApiV1UsersUserIdData): CancelablePromise<UsersReadUserByIdGetApiV1UsersUserIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserPatchApiV1UsersUserId(data: UsersUpdateUserPatchApiV1UsersUserIdData): CancelablePromise<UsersUpdateUserPatchApiV1UsersUserIdResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserDeleteApiV1UsersUserId(data: UsersDeleteUserDeleteApiV1UsersUserIdData): CancelablePromise<UsersDeleteUserDeleteApiV1UsersUserIdResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmailPostApiV1UtilsTestEmail(data: UtilsTestEmailPostApiV1UtilsTestEmailData): CancelablePromise<UtilsTestEmailPostApiV1UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}