// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token_post_api_v1_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DependenciesHealthResponse = {
    dependencies: Array<DependencyCheck>;
};

export type DependencyCheck = {
    name: string;
    status: DependencyStatus;
    /**
     * Sanitized dependency status detail.
     */
    detail: string;
};

export type DependencyStatus = 'HEALTHY' | 'DEGRADED' | 'UNAVAILABLE' | 'UNCONFIGURED' | 'UNKNOWN';

export type ErrorDetail = {
    code: string;
    message: string;
};

export type ErrorResponse = {
    error: ErrorDetail;
    request_id: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LiveHealthResponse = {
    status?: DependencyStatus;
    service?: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReadyHealthResponse = {
    status: DependencyStatus;
    dependencies: Array<DependencyCheck>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthLiveHealthGetApiV1HealthLiveResponse = (LiveHealthResponse);

export type HealthReadyHealthGetApiV1HealthReadyResponse = (ReadyHealthResponse);

export type HealthDependenciesHealthGetApiV1HealthDependenciesResponse = (DependenciesHealthResponse);

export type LoginLoginAccessTokenPostApiV1LoginAccessTokenData = {
    formData: Body_login_login_access_token_post_api_v1_login_access_token;
};

export type LoginLoginAccessTokenPostApiV1LoginAccessTokenResponse = (Token);

export type LoginTestTokenPostApiV1LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordPostApiV1PasswordRecoveryEmailData = {
    email: string;
};

export type LoginRecoverPasswordPostApiV1PasswordRecoveryEmailResponse = (Message);

export type LoginResetPasswordPostApiV1ResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordPostApiV1ResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailResponse = (string);

export type PrivateCreateUserPostApiV1PrivateUsersData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserPostApiV1PrivateUsersResponse = (UserPublic);

export type UsersReadUsersGetApiV1UsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersGetApiV1UsersResponse = (UsersPublic);

export type UsersCreateUserPostApiV1UsersData = {
    requestBody: UserCreate;
};

export type UsersCreateUserPostApiV1UsersResponse = (UserPublic);

export type UsersReadUserMeGetApiV1UsersMeResponse = (UserPublic);

export type UsersDeleteUserMeDeleteApiV1UsersMeResponse = (Message);

export type UsersUpdateUserMePatchApiV1UsersMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMePatchApiV1UsersMeResponse = (UserPublic);

export type UsersUpdatePasswordMePatchApiV1UsersMePasswordData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMePatchApiV1UsersMePasswordResponse = (Message);

export type UsersRegisterUserPostApiV1UsersSignupData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserPostApiV1UsersSignupResponse = (UserPublic);

export type UsersReadUserByIdGetApiV1UsersUserIdData = {
    userId: string;
};

export type UsersReadUserByIdGetApiV1UsersUserIdResponse = (UserPublic);

export type UsersUpdateUserPatchApiV1UsersUserIdData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserPatchApiV1UsersUserIdResponse = (UserPublic);

export type UsersDeleteUserDeleteApiV1UsersUserIdData = {
    userId: string;
};

export type UsersDeleteUserDeleteApiV1UsersUserIdResponse = (Message);

export type UtilsTestEmailPostApiV1UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailPostApiV1UtilsTestEmailResponse = (Message);