"""m4 data quality

Revision ID: 0014_m4_data_quality
Revises: 0013_m3_evidence_matrix
Create Date: 2026-08-04 02:29:29.578234

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0014_m4_data_quality'
down_revision = '0013_m3_evidence_matrix'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_approval_records_id_project',
        'approval_records',
        ['id', 'project_id'],
    )
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('USER_UPLOAD', 'PUBLIC_DATASET', 'DEMO_DATASET', 'MANUAL_ENTRY', name='dataset_source_type'), nullable=False),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_identifier', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('acquired_at', sa.Date(), nullable=True),
    sa.Column('license_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('license_status', sa.Enum('VERIFIED', 'DECLARED_BY_USER', 'UNKNOWN', 'RESTRICTED', name='dataset_license_status'), nullable=False),
    sa.Column('recommended_citation', sa.Text(), nullable=True),
    sa.Column('known_limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='dataset_status'), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('lock_version >= 1', name='ck_datasets_lock_version'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id', name='uq_datasets_id_project'),
    sa.UniqueConstraint('project_id', 'id', 'current_version_id', name='uq_datasets_current_scope')
    )
    op.create_index(op.f('ix_datasets_created_by'), 'datasets', ['created_by'], unique=False)
    op.create_index(op.f('ix_datasets_current_version_id'), 'datasets', ['current_version_id'], unique=False)
    op.create_index('ix_datasets_project_created', 'datasets', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_index('ix_datasets_project_status', 'datasets', ['project_id', 'status'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('version_type', sa.Enum('ORIGINAL', 'CLEANED', 'FILTERED', 'TRANSFORMED', 'DERIVED', name='dataset_version_type'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('file_format', sa.Enum('CSV', 'XLSX', name='dataset_file_format'), nullable=False),
    sa.Column('worksheet_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_worksheet_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('projection_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('schema_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('data_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('transformation_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('CREATING', 'VALIDATING', 'AVAILABLE', 'FAILED', 'INVALIDATED', 'DELETED', name='dataset_version_status'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(version_type = 'ORIGINAL' AND parent_version_id IS NULL AND transformation_id IS NULL) OR (version_type <> 'ORIGINAL' AND parent_version_id IS NOT NULL)", name='ck_dataset_versions_lineage'),
    sa.CheckConstraint("data_hash ~ '^[0-9a-f]{64}$'", name='ck_dataset_versions_data_hash'),
    sa.CheckConstraint("projection_hash IS NULL OR projection_hash ~ '^[0-9a-f]{64}$'", name='ck_dataset_versions_projection_hash'),
    sa.CheckConstraint("schema_hash IS NULL OR schema_hash ~ '^[0-9a-f]{64}$'", name='ck_dataset_versions_schema_hash'),
    sa.CheckConstraint('(invalidated_at IS NULL AND invalidation_reason IS NULL) OR (invalidated_at IS NOT NULL AND invalidation_reason IS NOT NULL)', name='ck_dataset_versions_invalidation_pair'),
    sa.CheckConstraint('column_count IS NULL OR column_count >= 0', name='ck_dataset_versions_columns'),
    sa.CheckConstraint('row_count IS NULL OR row_count >= 0', name='ck_dataset_versions_rows'),
    sa.CheckConstraint('version_number >= 1', name='ck_dataset_versions_number'),
    sa.ForeignKeyConstraint(['artifact_id', 'project_id'], ['artifacts.id', 'artifacts.project_id'], name='fk_dataset_versions_artifact_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id', 'project_id'], ['datasets.id', 'datasets.project_id'], name='fk_dataset_versions_dataset_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_version_id', 'project_id', 'dataset_id'], ['dataset_versions.id', 'dataset_versions.project_id', 'dataset_versions.dataset_id'], name='fk_dataset_versions_parent_scope', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version_number', name='uq_dataset_versions_number'),
    sa.UniqueConstraint('id', 'project_id', name='uq_dataset_versions_id_project'),
    sa.UniqueConstraint('project_id', 'dataset_id', 'id', name='uq_dataset_versions_scope')
    )
    op.create_index(op.f('ix_dataset_versions_artifact_id'), 'dataset_versions', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_created_by'), 'dataset_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_dataset_versions_data_hash'), 'dataset_versions', ['data_hash'], unique=False)
    op.create_index('ix_dataset_versions_dataset_created', 'dataset_versions', ['dataset_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_parent_version_id'), 'dataset_versions', ['parent_version_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_project_id'), 'dataset_versions', ['project_id'], unique=False)
    op.create_index('ix_dataset_versions_project_status', 'dataset_versions', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_dataset_versions_transformation_id'), 'dataset_versions', ['transformation_id'], unique=False)
    op.create_foreign_key(
        'fk_datasets_current_version_scope',
        'datasets',
        'dataset_versions',
        ['project_id', 'id', 'current_version_id'],
        ['project_id', 'dataset_id', 'id'],
        ondelete='RESTRICT',
    )
    op.create_table('cleaning_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATING', 'NEEDS_INPUT', 'READY', 'NEEDS_APPROVAL', 'APPROVED', 'REJECTED', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'INVALIDATED', name='cleaning_plan_status'), nullable=False),
    sa.Column('preview_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preview_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('affected_row_count', sa.Integer(), nullable=True),
    sa.Column('affected_column_count', sa.Integer(), nullable=True),
    sa.Column('source_model_invocation_id', sa.Uuid(), nullable=True),
    sa.Column('approval_record_id', sa.Uuid(), nullable=True),
    sa.Column('payload_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("payload_hash IS NULL OR payload_hash ~ '^[0-9a-f]{64}$'", name='ck_cleaning_plans_payload_hash'),
    sa.CheckConstraint("preview_hash IS NULL OR preview_hash ~ '^[0-9a-f]{64}$'", name='ck_cleaning_plans_preview_hash'),
    sa.CheckConstraint('lock_version >= 1', name='ck_cleaning_plans_lock'),
    sa.ForeignKeyConstraint(['approval_record_id', 'project_id'], ['approval_records.id', 'approval_records.project_id'], name='fk_cleaning_plans_approval_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_version_id', 'project_id'], ['dataset_versions.id', 'dataset_versions.project_id'], name='fk_cleaning_plans_version_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_model_invocation_id', 'project_id'], ['model_invocations.id', 'model_invocations.project_id'], name='fk_cleaning_plans_model_project', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id', name='uq_cleaning_plans_id_project')
    )
    op.create_index(op.f('ix_cleaning_plans_approval_record_id'), 'cleaning_plans', ['approval_record_id'], unique=False)
    op.create_index(op.f('ix_cleaning_plans_created_by'), 'cleaning_plans', ['created_by'], unique=False)
    op.create_index(op.f('ix_cleaning_plans_dataset_version_id'), 'cleaning_plans', ['dataset_version_id'], unique=False)
    op.create_index('ix_cleaning_plans_project_created', 'cleaning_plans', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_cleaning_plans_project_id'), 'cleaning_plans', ['project_id'], unique=False)
    op.create_index('ix_cleaning_plans_project_status', 'cleaning_plans', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_cleaning_plans_source_model_invocation_id'), 'cleaning_plans', ['source_model_invocation_id'], unique=False)
    op.create_table('data_quality_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('ruleset_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('rule_set_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ruleset_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'INVALIDATED', name='data_quality_run_status'), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('high_issue_count', sa.Integer(), nullable=False),
    sa.Column('processing_run_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("ruleset_hash ~ '^[0-9a-f]{64}$'", name='ck_data_quality_runs_ruleset_hash'),
    sa.CheckConstraint('high_issue_count >= 0', name='ck_data_quality_runs_high_count'),
    sa.CheckConstraint('issue_count >= 0', name='ck_data_quality_runs_issue_count'),
    sa.ForeignKeyConstraint(['dataset_version_id', 'project_id'], ['dataset_versions.id', 'dataset_versions.project_id'], name='fk_data_quality_runs_version_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processing_run_id', 'project_id'], ['processing_runs.id', 'processing_runs.project_id'], name='fk_data_quality_runs_processing_project', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id', name='uq_data_quality_runs_id_project')
    )
    op.create_index(op.f('ix_data_quality_runs_dataset_version_id'), 'data_quality_runs', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_data_quality_runs_processing_run_id'), 'data_quality_runs', ['processing_run_id'], unique=False)
    op.create_index('ix_data_quality_runs_project_created', 'data_quality_runs', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_data_quality_runs_project_id'), 'data_quality_runs', ['project_id'], unique=False)
    op.create_index('ix_data_quality_runs_project_status', 'data_quality_runs', ['project_id', 'status'], unique=False)
    op.create_table('dataset_columns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('column_order', sa.Integer(), nullable=False),
    sa.Column('inferred_type', sa.Enum('STRING', 'INTEGER', 'NUMERIC', 'BOOLEAN', 'DATE', 'DATETIME', 'CATEGORY', 'UNKNOWN', name='dataset_column_type'), nullable=False),
    sa.Column('confirmed_type', sa.Enum('STRING', 'INTEGER', 'NUMERIC', 'BOOLEAN', 'DATE', 'DATETIME', 'CATEGORY', 'UNKNOWN', name='dataset_column_type'), nullable=True),
    sa.Column('semantic_role', sa.Enum('ID', 'INDEPENDENT_VARIABLE', 'DEPENDENT_VARIABLE', 'CONTROL_VARIABLE', 'GROUP_VARIABLE', 'TIME_VARIABLE', 'WEIGHT', 'UNASSIGNED', name='dataset_semantic_role'), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('missing_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_identifier', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('confirmation_status', sa.Enum('UNCONFIRMED', 'CONFIRMED', 'NEEDS_REVIEW', name='dataset_column_confirmation_status'), nullable=False),
    sa.Column('unique_count', sa.Integer(), nullable=False),
    sa.Column('missing_ratio', sa.Float(), nullable=False),
    sa.Column('example_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inherited_from_column_id', sa.Uuid(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('column_order >= 1', name='ck_dataset_columns_order'),
    sa.CheckConstraint('lock_version >= 1', name='ck_dataset_columns_lock'),
    sa.CheckConstraint('missing_ratio >= 0 AND missing_ratio <= 1', name='ck_dataset_columns_missing_ratio'),
    sa.CheckConstraint('unique_count >= 0', name='ck_dataset_columns_unique_count'),
    sa.ForeignKeyConstraint(['dataset_version_id', 'project_id'], ['dataset_versions.id', 'dataset_versions.project_id'], name='fk_dataset_columns_version_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inherited_from_column_id', 'project_id'], ['dataset_columns.id', 'dataset_columns.project_id'], name='fk_dataset_columns_inherited_project', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'column_order', name='uq_dataset_columns_order'),
    sa.UniqueConstraint('dataset_version_id', 'source_name', name='uq_dataset_columns_source'),
    sa.UniqueConstraint('id', 'project_id', name='uq_dataset_columns_id_project')
    )
    op.create_index(op.f('ix_dataset_columns_dataset_version_id'), 'dataset_columns', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_dataset_columns_inherited_from_column_id'), 'dataset_columns', ['inherited_from_column_id'], unique=False)
    op.create_index('ix_dataset_columns_project_created', 'dataset_columns', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_dataset_columns_project_id'), 'dataset_columns', ['project_id'], unique=False)
    op.create_table('cleaning_plan_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('cleaning_plan_id', sa.Uuid(), nullable=False),
    sa.Column('action_order', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('KEEP_ROWS', 'DROP_ROWS', 'REPLACE_VALUE', 'MAP_CATEGORY', 'CAST_TYPE', 'MARK_MISSING', 'IMPUTE_VALUE', 'CONVERT_UNIT', 'RENAME_COLUMN', 'CREATE_DERIVED_COLUMN', name='cleaning_action_type'), nullable=False),
    sa.Column('selector_type', sa.Enum('ALL_ROWS', 'ISSUE_ROWS', 'VALUE_EQUALS', 'VALUE_IN', 'IS_NULL', 'IS_NOT_NULL', 'NUMERIC_RANGE', name='cleaning_selector_type'), nullable=False),
    sa.Column('target_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_selector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_issue_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preview_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preview_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='cleaning_risk_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('action_order >= 1', name='ck_cleaning_plan_actions_order'),
    sa.ForeignKeyConstraint(['cleaning_plan_id', 'project_id'], ['cleaning_plans.id', 'cleaning_plans.project_id'], name='fk_cleaning_plan_actions_plan_project', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cleaning_plan_id', 'action_order', name='uq_cleaning_plan_actions_order'),
    sa.UniqueConstraint('id', 'project_id', name='uq_cleaning_plan_actions_id_project')
    )
    op.create_index(op.f('ix_cleaning_plan_actions_cleaning_plan_id'), 'cleaning_plan_actions', ['cleaning_plan_id'], unique=False)
    op.create_index('ix_cleaning_plan_actions_project_created', 'cleaning_plan_actions', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_cleaning_plan_actions_project_id'), 'cleaning_plan_actions', ['project_id'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('data_quality_run_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('issue_type', sa.Enum('MISSING_VALUE', 'DUPLICATE_ROW', 'DUPLICATE_ID', 'CONSTANT_COLUMN', 'MIXED_TYPE', 'CATEGORY_INCONSISTENCY', 'OUT_OF_RANGE', 'EXTREME_VALUE', 'GROUP_IMBALANCE', 'SUSPICIOUS_UNIT', 'INVALID_DATE', 'POSSIBLE_SENSITIVE_FIELD', name='data_quality_issue_type'), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'INFO', name='data_quality_severity'), nullable=False),
    sa.Column('column_id', sa.Uuid(), nullable=True),
    sa.Column('affected_row_count', sa.Integer(), nullable=True),
    sa.Column('affected_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggested_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'PLANNED', 'RESOLVED', 'IGNORED', 'INVALIDATED', name='data_quality_issue_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('affected_row_count IS NULL OR affected_row_count >= 0', name='ck_data_quality_issues_affected_rows'),
    sa.ForeignKeyConstraint(['column_id', 'project_id'], ['dataset_columns.id', 'dataset_columns.project_id'], name='fk_data_quality_issues_column_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['data_quality_run_id', 'project_id'], ['data_quality_runs.id', 'data_quality_runs.project_id'], name='fk_data_quality_issues_run_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version_id', 'project_id'], ['dataset_versions.id', 'dataset_versions.project_id'], name='fk_data_quality_issues_version_project', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id', name='uq_data_quality_issues_id_project')
    )
    op.create_index(op.f('ix_data_quality_issues_column_id'), 'data_quality_issues', ['column_id'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_data_quality_run_id'), 'data_quality_issues', ['data_quality_run_id'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_dataset_version_id'), 'data_quality_issues', ['dataset_version_id'], unique=False)
    op.create_index('ix_data_quality_issues_project_created', 'data_quality_issues', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_project_id'), 'data_quality_issues', ['project_id'], unique=False)
    op.create_index('ix_data_quality_issues_project_status', 'data_quality_issues', ['project_id', 'status'], unique=False)
    op.create_table('data_transformations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('cleaning_plan_id', sa.Uuid(), nullable=False),
    sa.Column('approval_record_id', sa.Uuid(), nullable=False),
    sa.Column('source_dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('target_dataset_version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='data_transformation_status'), nullable=False),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('affected_row_count', sa.Integer(), nullable=True),
    sa.Column('affected_column_count', sa.Integer(), nullable=True),
    sa.Column('parameters_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('output_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('log_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('processing_run_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("parameters_hash ~ '^[0-9a-f]{64}$'", name='ck_data_transformations_parameters_hash'),
    sa.CheckConstraint("status <> 'COMPLETED' OR target_dataset_version_id IS NOT NULL", name='ck_data_transformations_completed_target'),
    sa.CheckConstraint('action_count >= 0', name='ck_data_transformations_action_count'),
    sa.ForeignKeyConstraint(['approval_record_id', 'project_id'], ['approval_records.id', 'approval_records.project_id'], name='fk_data_transformations_approval_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cleaning_plan_id', 'project_id'], ['cleaning_plans.id', 'cleaning_plans.project_id'], name='fk_data_transformations_plan_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['log_artifact_id', 'project_id'], ['artifacts.id', 'artifacts.project_id'], name='fk_data_transformations_log_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['output_artifact_id', 'project_id'], ['artifacts.id', 'artifacts.project_id'], name='fk_data_transformations_output_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processing_run_id', 'project_id'], ['processing_runs.id', 'processing_runs.project_id'], name='fk_data_transformations_processing_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_dataset_version_id', 'project_id'], ['dataset_versions.id', 'dataset_versions.project_id'], name='fk_data_transformations_source_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_dataset_version_id', 'project_id'], ['dataset_versions.id', 'dataset_versions.project_id'], name='fk_data_transformations_target_project', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cleaning_plan_id', name='uq_data_transformations_plan'),
    sa.UniqueConstraint('id', 'project_id', name='uq_data_transformations_id_project')
    )
    op.create_index(op.f('ix_data_transformations_approval_record_id'), 'data_transformations', ['approval_record_id'], unique=False)
    op.create_index(op.f('ix_data_transformations_cleaning_plan_id'), 'data_transformations', ['cleaning_plan_id'], unique=False)
    op.create_index(op.f('ix_data_transformations_log_artifact_id'), 'data_transformations', ['log_artifact_id'], unique=False)
    op.create_index(op.f('ix_data_transformations_output_artifact_id'), 'data_transformations', ['output_artifact_id'], unique=False)
    op.create_index(op.f('ix_data_transformations_processing_run_id'), 'data_transformations', ['processing_run_id'], unique=False)
    op.create_index('ix_data_transformations_project_created', 'data_transformations', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_data_transformations_project_id'), 'data_transformations', ['project_id'], unique=False)
    op.create_index('ix_data_transformations_project_status', 'data_transformations', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_data_transformations_source_dataset_version_id'), 'data_transformations', ['source_dataset_version_id'], unique=False)
    op.create_index(op.f('ix_data_transformations_target_dataset_version_id'), 'data_transformations', ['target_dataset_version_id'], unique=False)
    op.create_foreign_key(
        'fk_dataset_versions_transformation_project',
        'dataset_versions',
        'data_transformations',
        ['transformation_id', 'project_id'],
        ['id', 'project_id'],
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_dataset_versions_transformation_project',
        'dataset_versions',
        type_='foreignkey',
    )
    op.drop_constraint(
        'fk_datasets_current_version_scope', 'datasets', type_='foreignkey'
    )
    op.drop_index(op.f('ix_data_transformations_target_dataset_version_id'), table_name='data_transformations')
    op.drop_index(op.f('ix_data_transformations_source_dataset_version_id'), table_name='data_transformations')
    op.drop_index('ix_data_transformations_project_status', table_name='data_transformations')
    op.drop_index(op.f('ix_data_transformations_project_id'), table_name='data_transformations')
    op.drop_index('ix_data_transformations_project_created', table_name='data_transformations')
    op.drop_index(op.f('ix_data_transformations_processing_run_id'), table_name='data_transformations')
    op.drop_index(op.f('ix_data_transformations_output_artifact_id'), table_name='data_transformations')
    op.drop_index(op.f('ix_data_transformations_log_artifact_id'), table_name='data_transformations')
    op.drop_index(op.f('ix_data_transformations_cleaning_plan_id'), table_name='data_transformations')
    op.drop_index(op.f('ix_data_transformations_approval_record_id'), table_name='data_transformations')
    op.drop_table('data_transformations')
    op.drop_index('ix_data_quality_issues_project_status', table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_project_id'), table_name='data_quality_issues')
    op.drop_index('ix_data_quality_issues_project_created', table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_dataset_version_id'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_data_quality_run_id'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_column_id'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_cleaning_plan_actions_project_id'), table_name='cleaning_plan_actions')
    op.drop_index('ix_cleaning_plan_actions_project_created', table_name='cleaning_plan_actions')
    op.drop_index(op.f('ix_cleaning_plan_actions_cleaning_plan_id'), table_name='cleaning_plan_actions')
    op.drop_table('cleaning_plan_actions')
    op.drop_index(op.f('ix_dataset_columns_project_id'), table_name='dataset_columns')
    op.drop_index('ix_dataset_columns_project_created', table_name='dataset_columns')
    op.drop_index(op.f('ix_dataset_columns_inherited_from_column_id'), table_name='dataset_columns')
    op.drop_index(op.f('ix_dataset_columns_dataset_version_id'), table_name='dataset_columns')
    op.drop_table('dataset_columns')
    op.drop_index('ix_data_quality_runs_project_status', table_name='data_quality_runs')
    op.drop_index(op.f('ix_data_quality_runs_project_id'), table_name='data_quality_runs')
    op.drop_index('ix_data_quality_runs_project_created', table_name='data_quality_runs')
    op.drop_index(op.f('ix_data_quality_runs_processing_run_id'), table_name='data_quality_runs')
    op.drop_index(op.f('ix_data_quality_runs_dataset_version_id'), table_name='data_quality_runs')
    op.drop_table('data_quality_runs')
    op.drop_index(op.f('ix_cleaning_plans_source_model_invocation_id'), table_name='cleaning_plans')
    op.drop_index('ix_cleaning_plans_project_status', table_name='cleaning_plans')
    op.drop_index(op.f('ix_cleaning_plans_project_id'), table_name='cleaning_plans')
    op.drop_index('ix_cleaning_plans_project_created', table_name='cleaning_plans')
    op.drop_index(op.f('ix_cleaning_plans_dataset_version_id'), table_name='cleaning_plans')
    op.drop_index(op.f('ix_cleaning_plans_created_by'), table_name='cleaning_plans')
    op.drop_index(op.f('ix_cleaning_plans_approval_record_id'), table_name='cleaning_plans')
    op.drop_table('cleaning_plans')
    op.drop_index(op.f('ix_dataset_versions_transformation_id'), table_name='dataset_versions')
    op.drop_index('ix_dataset_versions_project_status', table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_project_id'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_parent_version_id'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_index('ix_dataset_versions_dataset_created', table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_data_hash'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_created_by'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_artifact_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index('ix_datasets_project_status', table_name='datasets')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    op.drop_index('ix_datasets_project_created', table_name='datasets')
    op.drop_index(op.f('ix_datasets_current_version_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_created_by'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_constraint(
        'uq_approval_records_id_project', 'approval_records', type_='unique'
    )
    for enum_name in (
        'data_transformation_status',
        'data_quality_issue_status',
        'data_quality_severity',
        'data_quality_issue_type',
        'cleaning_risk_level',
        'cleaning_selector_type',
        'cleaning_action_type',
        'dataset_column_confirmation_status',
        'dataset_semantic_role',
        'dataset_column_type',
        'data_quality_run_status',
        'cleaning_plan_status',
        'dataset_version_status',
        'dataset_file_format',
        'dataset_version_type',
        'dataset_status',
        'dataset_license_status',
        'dataset_source_type',
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
