/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SystemStatusRouteImport } from './routes/system-status'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects.index'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout/projects.$projectId'
import { Route as LayoutProjectsProjectIdAnalysisRouteImport } from './routes/_layout/projects.$projectId_.analysis'
import { Route as LayoutProjectsProjectIdDataRouteImport } from './routes/_layout/projects.$projectId_.data'
import { Route as LayoutProjectsProjectIdLiteratureRouteImport } from './routes/_layout/projects.$projectId_.literature'
import { Route as LayoutProjectsProjectIdManuscriptRouteImport } from './routes/_layout/projects.$projectId_.manuscript'
import { Route as LayoutProjectsProjectIdResearchQuestionRouteImport } from './routes/_layout/projects.$projectId_.research-question'
import { Route as LayoutProjectsProjectIdDocumentsDocumentIdRouteImport } from './routes/_layout/projects.$projectId_.documents.$documentId'
import { Route as LayoutProjectsProjectIdQueryPlansQueryPlanIdRouteImport } from './routes/_layout/projects.$projectId_.query-plans.$queryPlanId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutProjectsProjectIdAnalysisRoute =
  LayoutProjectsProjectIdAnalysisRouteImport.update({
    id: '/$projectId_/analysis',
    path: '/$projectId/analysis',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)
const LayoutProjectsProjectIdDataRoute =
  LayoutProjectsProjectIdDataRouteImport.update({
    id: '/$projectId_/data',
    path: '/$projectId/data',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)
const LayoutProjectsProjectIdLiteratureRoute =
  LayoutProjectsProjectIdLiteratureRouteImport.update({
    id: '/$projectId_/literature',
    path: '/$projectId/literature',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)
const LayoutProjectsProjectIdManuscriptRoute =
  LayoutProjectsProjectIdManuscriptRouteImport.update({
    id: '/$projectId_/manuscript',
    path: '/$projectId/manuscript',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)
const LayoutProjectsProjectIdResearchQuestionRoute =
  LayoutProjectsProjectIdResearchQuestionRouteImport.update({
    id: '/$projectId_/research-question',
    path: '/$projectId/research-question',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)
const LayoutProjectsProjectIdDocumentsDocumentIdRoute =
  LayoutProjectsProjectIdDocumentsDocumentIdRouteImport.update({
    id: '/$projectId_/documents/$documentId',
    path: '/$projectId/documents/$documentId',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)
const LayoutProjectsProjectIdQueryPlansQueryPlanIdRoute =
  LayoutProjectsProjectIdQueryPlansQueryPlanIdRouteImport.update({
    id: '/$projectId_/query-plans/$queryPlanId',
    path: '/$projectId/query-plans/$queryPlanId',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-status': typeof SystemStatusRoute
  '/admin': typeof LayoutAdminRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/projects/': typeof LayoutProjectsIndexRoute
  '/projects/$projectId/analysis': typeof LayoutProjectsProjectIdAnalysisRoute
  '/projects/$projectId/data': typeof LayoutProjectsProjectIdDataRoute
  '/projects/$projectId/literature': typeof LayoutProjectsProjectIdLiteratureRoute
  '/projects/$projectId/manuscript': typeof LayoutProjectsProjectIdManuscriptRoute
  '/projects/$projectId/research-question': typeof LayoutProjectsProjectIdResearchQuestionRoute
  '/projects/$projectId/documents/$documentId': typeof LayoutProjectsProjectIdDocumentsDocumentIdRoute
  '/projects/$projectId/query-plans/$queryPlanId': typeof LayoutProjectsProjectIdQueryPlansQueryPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-status': typeof SystemStatusRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/projects/$projectId/analysis': typeof LayoutProjectsProjectIdAnalysisRoute
  '/projects/$projectId/data': typeof LayoutProjectsProjectIdDataRoute
  '/projects/$projectId/literature': typeof LayoutProjectsProjectIdLiteratureRoute
  '/projects/$projectId/manuscript': typeof LayoutProjectsProjectIdManuscriptRoute
  '/projects/$projectId/research-question': typeof LayoutProjectsProjectIdResearchQuestionRoute
  '/projects/$projectId/documents/$documentId': typeof LayoutProjectsProjectIdDocumentsDocumentIdRoute
  '/projects/$projectId/query-plans/$queryPlanId': typeof LayoutProjectsProjectIdQueryPlansQueryPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-status': typeof SystemStatusRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/projects': typeof LayoutProjectsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/projects/$projectId_/analysis': typeof LayoutProjectsProjectIdAnalysisRoute
  '/_layout/projects/$projectId_/data': typeof LayoutProjectsProjectIdDataRoute
  '/_layout/projects/$projectId_/literature': typeof LayoutProjectsProjectIdLiteratureRoute
  '/_layout/projects/$projectId_/manuscript': typeof LayoutProjectsProjectIdManuscriptRoute
  '/_layout/projects/$projectId_/research-question': typeof LayoutProjectsProjectIdResearchQuestionRoute
  '/_layout/projects/$projectId_/documents/$documentId': typeof LayoutProjectsProjectIdDocumentsDocumentIdRoute
  '/_layout/projects/$projectId_/query-plans/$queryPlanId': typeof LayoutProjectsProjectIdQueryPlansQueryPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/system-status'
    | '/admin'
    | '/projects'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/analysis'
    | '/projects/$projectId/data'
    | '/projects/$projectId/literature'
    | '/projects/$projectId/manuscript'
    | '/projects/$projectId/research-question'
    | '/projects/$projectId/documents/$documentId'
    | '/projects/$projectId/query-plans/$queryPlanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/system-status'
    | '/admin'
    | '/settings'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/analysis'
    | '/projects/$projectId/data'
    | '/projects/$projectId/literature'
    | '/projects/$projectId/manuscript'
    | '/projects/$projectId/research-question'
    | '/projects/$projectId/documents/$documentId'
    | '/projects/$projectId/query-plans/$queryPlanId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/system-status'
    | '/_layout/admin'
    | '/_layout/projects'
    | '/_layout/settings'
    | '/_layout/projects/$projectId'
    | '/_layout/projects/'
    | '/_layout/projects/$projectId_/analysis'
    | '/_layout/projects/$projectId_/data'
    | '/_layout/projects/$projectId_/literature'
    | '/_layout/projects/$projectId_/manuscript'
    | '/_layout/projects/$projectId_/research-question'
    | '/_layout/projects/$projectId_/documents/$documentId'
    | '/_layout/projects/$projectId_/query-plans/$queryPlanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SystemStatusRoute: typeof SystemStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-status': {
      id: '/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$projectId': {
      id: '/_layout/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$projectId_/analysis': {
      id: '/_layout/projects/$projectId_/analysis'
      path: '/$projectId/analysis'
      fullPath: '/projects/$projectId/analysis'
      preLoaderRoute: typeof LayoutProjectsProjectIdAnalysisRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$projectId_/data': {
      id: '/_layout/projects/$projectId_/data'
      path: '/$projectId/data'
      fullPath: '/projects/$projectId/data'
      preLoaderRoute: typeof LayoutProjectsProjectIdDataRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$projectId_/literature': {
      id: '/_layout/projects/$projectId_/literature'
      path: '/$projectId/literature'
      fullPath: '/projects/$projectId/literature'
      preLoaderRoute: typeof LayoutProjectsProjectIdLiteratureRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$projectId_/manuscript': {
      id: '/_layout/projects/$projectId_/manuscript'
      path: '/$projectId/manuscript'
      fullPath: '/projects/$projectId/manuscript'
      preLoaderRoute: typeof LayoutProjectsProjectIdManuscriptRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$projectId_/research-question': {
      id: '/_layout/projects/$projectId_/research-question'
      path: '/$projectId/research-question'
      fullPath: '/projects/$projectId/research-question'
      preLoaderRoute: typeof LayoutProjectsProjectIdResearchQuestionRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$projectId_/documents/$documentId': {
      id: '/_layout/projects/$projectId_/documents/$documentId'
      path: '/$projectId/documents/$documentId'
      fullPath: '/projects/$projectId/documents/$documentId'
      preLoaderRoute: typeof LayoutProjectsProjectIdDocumentsDocumentIdRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$projectId_/query-plans/$queryPlanId': {
      id: '/_layout/projects/$projectId_/query-plans/$queryPlanId'
      path: '/$projectId/query-plans/$queryPlanId'
      fullPath: '/projects/$projectId/query-plans/$queryPlanId'
      preLoaderRoute: typeof LayoutProjectsProjectIdQueryPlansQueryPlanIdRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
  }
}

interface LayoutProjectsRouteChildren {
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRoute
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
  LayoutProjectsProjectIdAnalysisRoute: typeof LayoutProjectsProjectIdAnalysisRoute
  LayoutProjectsProjectIdDataRoute: typeof LayoutProjectsProjectIdDataRoute
  LayoutProjectsProjectIdLiteratureRoute: typeof LayoutProjectsProjectIdLiteratureRoute
  LayoutProjectsProjectIdManuscriptRoute: typeof LayoutProjectsProjectIdManuscriptRoute
  LayoutProjectsProjectIdResearchQuestionRoute: typeof LayoutProjectsProjectIdResearchQuestionRoute
  LayoutProjectsProjectIdDocumentsDocumentIdRoute: typeof LayoutProjectsProjectIdDocumentsDocumentIdRoute
  LayoutProjectsProjectIdQueryPlansQueryPlanIdRoute: typeof LayoutProjectsProjectIdQueryPlansQueryPlanIdRoute
}

const LayoutProjectsRouteChildren: LayoutProjectsRouteChildren = {
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRoute,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
  LayoutProjectsProjectIdAnalysisRoute: LayoutProjectsProjectIdAnalysisRoute,
  LayoutProjectsProjectIdDataRoute: LayoutProjectsProjectIdDataRoute,
  LayoutProjectsProjectIdLiteratureRoute:
    LayoutProjectsProjectIdLiteratureRoute,
  LayoutProjectsProjectIdManuscriptRoute:
    LayoutProjectsProjectIdManuscriptRoute,
  LayoutProjectsProjectIdResearchQuestionRoute:
    LayoutProjectsProjectIdResearchQuestionRoute,
  LayoutProjectsProjectIdDocumentsDocumentIdRoute:
    LayoutProjectsProjectIdDocumentsDocumentIdRoute,
  LayoutProjectsProjectIdQueryPlansQueryPlanIdRoute:
    LayoutProjectsProjectIdQueryPlansQueryPlanIdRoute,
}

const LayoutProjectsRouteWithChildren = LayoutProjectsRoute._addFileChildren(
  LayoutProjectsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutProjectsRoute: typeof LayoutProjectsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutProjectsRoute: LayoutProjectsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SystemStatusRoute: SystemStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
