/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router. Regenerate it during the Vite build.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SignupRouteImport } from "./routes/signup"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as RecoverPasswordRouteImport } from "./routes/recover-password"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as LayoutRouteImport } from "./routes/_layout"
import { Route as LayoutIndexRouteImport } from "./routes/_layout/index"
import { Route as LayoutSettingsRouteImport } from "./routes/_layout/settings"
import { Route as LayoutAdminRouteImport } from "./routes/_layout/admin"

const SignupRoute = SignupRouteImport.update({ id: "/signup", path: "/signup", getParentRoute: () => rootRouteImport } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({ id: "/reset-password", path: "/reset-password", getParentRoute: () => rootRouteImport } as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({ id: "/recover-password", path: "/recover-password", getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: "/login", path: "/login", getParentRoute: () => rootRouteImport } as any)
const LayoutRoute = LayoutRouteImport.update({ id: "/_layout", getParentRoute: () => rootRouteImport } as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({ id: "/", path: "/", getParentRoute: () => LayoutRoute } as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({ id: "/settings", path: "/settings", getParentRoute: () => LayoutRoute } as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({ id: "/admin", path: "/admin", getParentRoute: () => LayoutRoute } as any)

const LayoutRouteChildren = {
  LayoutAdminRoute,
  LayoutSettingsRoute,
  LayoutIndexRoute,
}
const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren)
const rootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<any>()
